name: Integration Tests

on: [push]

jobs:
#  build-linux:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v2
#        with:
#          java-version: 1.8
#          distribution: adopt
#      - name: Build and run tests
#        run: mvn -B verify
#
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt
      - name: Set up JRE 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt
          java-package: jre
      - name: Build and run tests
        run: |
          $env:JAVA_HOME = "C:\hostedtoolcache\windows\Java_Adopt_jdk\8.0.292-10\x64"
          mvn -B package
          $env:JAVA_HOME
          $env:PATH
          dir $env:JAVA_HOME
          dir $env:JAVA_HOME\bin
          # dir $env:JAVA_HOME\jre\bin
          which java
          java -version
          java -jar target\extract-tls-secrets-4.1.0-SNAPSHOT.jar list
